bin/dapsync: Improve reliability

diff --git a/bin/dapsync b/bin/dapsync
--- a/bin/dapsync
+++ b/bin/dapsync
@@ -1,7 +1,13 @@
 #!/bin/sh
-set -e # Fail on command error
+set -eu
 
+# Fail if already mounted
+mountpoint /mnt/disk && exit 1
 sudo mount -vo rw,fmask=0133,dmask=0022,gid="$(id -g)",uid="$(id -u)" UUID=4D3D-2FC5 /mnt/disk
+
+# Unmount on exit or failure
+trap 'sudo umount -v /mnt/disk' EXIT
+trap exit INT HUP TERM
 
 if [ "$(cat /etc/hostname)" = "mir" ]; then
   musicsource="$HOME/Music/"
@@ -22,6 +28,3 @@ if [ "$1" = "--checksum" ]; then
 else
   rsync -thrv --info=progress2 "$musicsource" /mnt/disk/Music --delete --modify-window=1 --fuzzy --delete-delay
 fi
-
-sudo umount -v /mnt/disk
-
